setGeneric("approved", function(object, ...) standardGeneric("approved"))
setGeneric("id", function(object, ...) standardGeneric("id"))
setGeneric("composition", function(object, ...) standardGeneric("composition"))
setGeneric("deltaAvgMass", function(object, ...)
           standardGeneric("deltaAvgMass"))
setGeneric("deltaMonoMass", function(object, ...)
           standardGeneric("deltaMonoMass"))
setGeneric("name", function(object, ...) standardGeneric("name"))
setGeneric("specificity", function(object, ...) standardGeneric("specificity"))
setGeneric("references", function(object, ...) standardGeneric("references"))
