#' Find Modification by id/title.
#'
#' This function allows to query the unimod database by the \emph{id} or
#' \emph{title} of specific modification and returns an
#' \code{\linkS4class{Modification}} object.
#'
#' @param id integer, id of the modification.
#' @return object of class Modification.
#' @seealso \code{\linkS4class{Modification}}.
#' @references \url{http://www.unimod.org/modifications_list.php}
#' @export
#' @rdname umodId
#' @aliases umodId umodTitle
#' @examples
#' library("unimod")
#'
#' umodId(1)
#'
#' umodTitle("Acetyl")
#'
umodId <- function(id) {
  .umodId(.unimodDb(), id)
}

#' @param title character, title of the modification.
#' @rdname umodId
#' @export
umodTitle <- function(title) {
  .umodTitle(.unimodDb(), title)
}

#' internal function to query Modification by id
#'
#' @param xml xml_document (generated by .unimodDb())
#' @param id integer, unimod id
#' @return Modification
#' @noRd
.umodId <- function(xml, id) {
  if (!is(xml, "xml_document")) {
    stop("'xml' must be an 'xml_document'.")
  }
  if (!is.numeric(id)) {
    stop("'id' has to be numeric.")
  }
  if (length(id) != 1L) {
    stop("'id' has to be of length one.")
  }
  if (id < 0L) {
    stop("'id' has to be positive.")
  }
  x <- xml_find_all(xml,
    sprintf("//umod:modifications/umod:mod[@record_id=\"%d\"]", id))
  if (!length(x)) {
    stop("Id ", id, " was not found!")
  } else {
    Modification(x[[1L]])
  }
}

#' internal function to query Modification by title
#'
#' @param xml xml_document (generated by .unimodDb())
#' @param title character, unimod title
#' @return Modification
#' @noRd
.umodTitle <- function(xml, title) {
  if (!is(xml, "xml_document")) {
    stop("'xml' must be an 'xml_document'.")
  }
  if (!is.character(title)) {
    stop("'title' has to be a character.")
  }
  if (length(title) != 1L) {
    stop("'character' has to be of length one.")
  }
  x <- xml_find_all(xml,
    sprintf("//umod:modifications/umod:mod[@title=\"%s\"]", title))
  if (!length(x)) {
    stop("Title ", title, " was not found!")
  } else {
    Modification(x[[1L]])
  }
}
