#' Find Modification by id/name/title.
#'
#' This function allows to query the unimod database by the \emph{id} or
#' \emph{title} of specific modification and returns an
#' \code{\linkS4class{Modification}} object.
#'
#' @param id integer, id of the modification.
#' @return object of class Modification.
#' @seealso \code{\linkS4class{Modification}}.
#' @references \url{http://www.unimod.org/modifications_list.php}
#' @export
#' @rdname umodId
#' @aliases umodId umodTitle
#' @examples
#' library("unimod")
#'
#' umodId(1)
#'
#' umodTitle("Acetyl")
#'
umodId <- function(id) {
  .umodId(.unimodDb(), id)
}

#' @param name character, PSI-MS name/title of the modification.
#' @rdname umodId
#' @export
umodName <- function(name) {
  .umodTitle(.unimodDb(), name)
}

#' @param title character, PSI-MS name/title of the modification.
#' @rdname umodId
#' @export
umodTitle <- function(title) {
  .umodTitle(.unimodDb(), title)
}


#' internal function to query Modification by id
#'
#' @param xml xml_document (generated by .unimodDb())
#' @param id integer, unimod id
#' @return Modification
#' @noRd
.umodId <- function(xml, id) {
  if (!is(xml, "xml_document")) {
    stop("'xml' must be an 'xml_document'.")
  }
  if (!is.numeric(id)) {
    stop("'id' has to be numeric.")
  }
  if (length(id) != 1L) {
    stop("'id' has to be of length one.")
  }
  if (id < 0L) {
    stop("'id' has to be positive.")
  }
  node <- xml_find_first(xml,
    sprintf("//umod:modifications/umod:mod[@record_id=\"%d\"]", id))
  if (!length(node)) {
    stop("Id ", id, " was not found!")
  } else {
    .Modification(node)
  }
}

#' internal function to query Modification by title
#'
#' @param xml xml_document (generated by .unimodDb())
#' @param title character, unimod title
#' @return Modification
#' @noRd
.umodTitle <- function(xml, title) {
  if (!is(xml, "xml_document")) {
    stop("'xml' must be an 'xml_document'.")
  }
  if (!is.character(title)) {
    stop("'title' has to be a character.")
  }
  if (length(title) != 1L) {
    stop("'character' has to be of length one.")
  }
  node <- xml_find_first(xml,
    sprintf("//umod:modifications/umod:mod[@title=\"%s\"]", title))
 if (!length(node)) {
    stop("Title ", title, " was not found!")
  } else {
    .Modification(node)
  }
}

#' internal function to query title/id/lastmod
#'
#' @param xml xml_nodeset, <mod>
#' @return double
#' @noRd
.title <- function(xml) {
  setNames(xml_attrs(xml)[c("record_id", "title", "full_name",
                            "date_time_modified", "approved")],
           c("id", "name", "description", "lastModified", "approved"))
}

#' internal function to query delta mass
#'
#' @param xml xml_nodeset, <mod>
#' @return double
#' @noRd
.delta <- function(xml) {
  node <- xml_find_first(xml, ".//umod:delta")
  setNames(as.double(xml_attrs(node)[c("avge_mass", "mono_mass")]),
           c("avgMass", "monoMass"))
}

#' internal function to query composition
#'
#' @param xml xml_nodeset, <mod>
#' @return list, delta masses and composition as named vector
#' @noRd
.composition <- function(xml) {
  nodes <- xml_find_all(xml, ".//umod:delta/umod:element")
  composition <- do.call(rbind, xml_attrs(nodes))
  setNames(as.integer(composition[, "number"]), composition[, "symbol"])
}

#' internal function to query specificity
#'
#' @param xml xml_nodeset, <mod>
#' @return data.frame
#' @noRd
.specificity <- function(xml) {
  nodes <- xml_find_all(xml, ".//umod:specificity")
  sp <- do.call(rbind, xml_attrs(nodes))
  sp <- sp[order(sp[, "spec_group"]),, drop=FALSE]
  data.frame(site=sp[, "site"],
             position=sp[, "position"],
             classification=sp[, "classification"],
             hidden=sp[, "hidden"] == "1",
             group=as.integer(sp[, "spec_group"]),
             stringsAsFactors=FALSE, row.names=seq(nrow(sp)))
}

#' internal function to query references
#'
#' @param xml xml_nodeset, <mod>
#' @return data.frame
#' @noRd
.xref <- function(xml) {
  nodes <- xml_find_all(xml, ".//umod:xref")
  data.frame(text=xml_text(xml_find_all(nodes, ".//umod:text")),
             source=xml_text(xml_find_all(nodes, ".//umod:source")),
             url=xml_text(xml_find_all(nodes, ".//umod:url")),
             stringsAsFactors=FALSE)
}
